{
 "title": "Financial Engine Overvie",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput (Tx / seg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(transactions_processed_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eventos en DLT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transactions_dlt_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicados Bloqueados (Redis)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transactions_duplicates_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transacciones Exitosas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transactions_processed_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}